name: get secret from secret manager
on:
  workflow_dispatch
jobs:
  get-secret:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

  
    steps:
      
      - uses: actions/checkout@v3
      - id: 'auth' 
        name:  authenticate gke 
        uses: 'google-github-actions/auth@v1'
        with:
        
          workload_identity_provider: 'projects/499613830332/locations/global/workloadIdentityPool/deel/providers/github'
          service_account: 'github-actions@deel-home-task-1.iam.gserviceaccount.com'
      - name: 'setup cloud sdk'
        uses: google-github-actions/setup-gcloud@v1
     
      - id: 'gcloud'
        name: 'gcloud'
        run: |
          gcloud secrets versions access "latest" --secret "my-secret"