name: deploy-deel
on: push

env:
  APP_NAME: deel

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    env:
      DEPLOY_ENVIRONMENT: staging
    steps:
      -
        uses: actions/checkout@v2
      -
        uses: jmagnusson/deploy-helm-gke-action@v1
        with:
          docker-image-repo: ${{ secrets.GITHUB_USERNAME }}/${{ secrets.GITHUB_TOKEN }}
          docker-image-tag: ${{ github.sha }}
          helm-release-name: ${{ env.APP_NAME }}
          helm-chart-path: ./deel/${{ env.APP_NAME }}
          #helm-vars-folder: helm_vars/${{ env.DEPLOY_ENVIRONMENT }}
          gke-project: deel-home-task-1
          gke-cluster: deel-cluster
          gke-zone: us-east5-a
          gke-sa-key: ${{ secrets.KUBECONFIG }}
