name: Deploy Helm Chart to GKE

on:
  push:
    #branches:
     # - eladtamari-pathc-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Authenticate using service account key
      run: |
        printf "${{ secrets.SA_KEY }}" | base64 -d > "/home/runner/gcloud-key.json"
        gcloud auth activate-service-account --key-file="/home/runner/gcloud-key.json"
        gcloud config set project ${{ secrets.GKE_PROJECT }}
    #- name: Set up GCloud CLI
     # uses: google-github-actions/setup-gcloud@v1
     # with:
     #   version: '428.0.0'
     #   service_account_key: ${{ secrets.SA_KEY }}
     #   project_id: deel-home-task-1
    

    - name: Authenticate to GKE
      run: |
        gcloud container clusters get-credentials deel-cluster --zone us-east5-a --project deel-home-task-1
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
    - name: Deploy Helm Chart
      run: |
        helm upgrade --install my-release ./chart --namespace default
