name: get secret from secret manager
on:
  push
jobs:
  get-secret:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

  
    steps:
      
      - uses: actions/checkout@v4
      - id: 'auth' 
        name:  authenticate gke 
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          token_format: "access_token"
          create_credentials_file: true
          workload_identity_provider: 'projects/499613830332/locations/global/workloadIdentityPools/deel/providers/github'
          service_account: 'github-actions@deel-home-task-1.iam.gserviceaccount.com'
      - name: 'setup cloud sdk'
        uses: google-github-actions/setup-gcloud@v1
     
      - id: 'gcloud'
        name: 'gcloud'
        run: |-
            gcloud secrets versions access "latest" --secret "my-secret"
            #gcloud compute instances list
      #- id: get-gke-credentials
      #  uses: google-github-actions/get-gke-credentials@v0.4.0
      #  with:
      #    project_id: 'deel-home-task-1'
      #    cluster_name: 'deel-cluster'
      #    location: 'us-east5-a'
